# Generated by Django 5.1.5 on 2026-09-22 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Identificador único del registro, p. ej. VJ-00001",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "placa",
                    models.CharField(
                        db_index=True,
                        help_text="Placa del vehículo, p. ej. ABC123",
                        max_length=10,
                        verbose_name="Placa",
                    ),
                ),
                (
                    "tipo_vehiculo",
                    models.CharField(
                        choices=[
                            ("Turbo", "Turbo"),
                            ("Sencillo", "Sencillo"),
                            ("Eléctrico", "Eléctrico"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo de vehículo",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(db_index=True, verbose_name="Fecha de inicio"),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de fin"
                    ),
                ),
                (
                    "numero_entregas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de entregas"
                    ),
                ),
                (
                    "facturacion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Facturación",
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, verbose_name="Observación"),
                ),
                ("cliente", models.CharField(max_length=100, verbose_name="Cliente")),
                (
                    "validado",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Validado"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehiculos_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="HistorialValidacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_nuevo",
                    models.BooleanField(verbose_name="Nuevo estado validado"),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del cambio"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validaciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_validaciones",
                        to="viajes.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de validación",
                "verbose_name_plural": "Historial de validaciones",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddIndex(
            model_name="vehiculo",
            index=models.Index(
                fields=["-fecha_inicio"], name="viajes_vehi_fecha_i_b67ec3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiculo",
            index=models.Index(
                fields=["validado", "-fecha_inicio"],
                name="viajes_vehi_validad_13429c_idx",
            ),
        ),
    ]
