# Generated by Django 5.1.5 on 2026-09-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='destino',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='destino_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud destino'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='destino_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud destino'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='origen',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='origen_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud origen'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='origen_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud origen'),
        ),
    ]
